name: weatherforecast
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.3
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  provider: ^6.1.4
  google_fonts: ^6.2.1
  flutter_map: ^8.1.1
  geocoding: ^3.0.0
  latlong2: ^0.9.1
  carousel_slider: ^5.0.0
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/icons/
      - .env


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_dammay.jpg"  # Đường dẫn đến logo của bạn


